export const USER_ACTIONS = {
    LOGGED_IN: 'LOGGED_IN',
    UPDATE: 'UPDATE_USER_DATA',
    LOGOUT: 'LOGOUT',
    CLEAR: 'CLEAR',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    AUTHENTICATION: 'AUTHENTICATION',

    GET_USER: "GET_USER",
    CHAT_WITH: "CHAT_WITH",
    MESSAGES: "MESSAGES"
};
